import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {ReduxProvider} from "@/redux/provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type TypeRoot = { children: React.ReactNode; };
export default function RootLayout({children,}: Readonly<TypeRoot>) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
        </body>
        </html>
    );
}
