import type {Metadata} from "next";
import {Inter} from "next/font/google";
// import "../them/head";

// import "../them/css/bootstrap-reboot.min.css";
// import "../them/css/bootstrap-grid.min.css";
// import "../them/css/owl.carousel.min.css";
// import "../them/css/jquery.mCustomScrollbar.min.css";
// import "../them/css/nouislider.min.css";
// // import "../them/css/ionicons.min.css";
// import "../them/css/plyr.css";
// import "../them/css/photoswipe.css";
// import "../them/css/default-skin.css";
// import "../them/css/main.css";
// import "../them/css/";


import "./globals.css";
import React from "react";
import {ReduxProvider} from "@/redux/provider";
import HeaderComponent from "@/components/Header/HeaderComponent";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type TypeRoot = { children: React.ReactNode; };
export default function RootLayout({children,}: Readonly<TypeRoot>) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <ReduxProvider>
            <HeaderComponent/>
            {children}
        </ReduxProvider>
        </body>
        </html>
    );
}
